auth:
  registry.hub.docker.com:
    username: $USERNAME
    password: $PASSWORD
images:
   k8s.gcr.io/metrics-server/metrics-server: finleyma/metrics-server
   registry.k8s.io/csi-secrets-store/driver: finleyma/driver